USE [master]
GO
/****** Object:  Database [video02]    Script Date: 12/12/2014 1:09:50 AM ******/
CREATE DATABASE [video02];
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [video02].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [video02] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [video02] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [video02] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [video02] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [video02] SET ARITHABORT OFF 
GO
ALTER DATABASE [video02] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [video02] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [video02] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [video02] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [video02] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [video02] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [video02] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [video02] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [video02] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [video02] SET  ENABLE_BROKER 
GO
ALTER DATABASE [video02] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [video02] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [video02] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [video02] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [video02] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [video02] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [video02] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [video02] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [video02] SET  MULTI_USER 
GO
ALTER DATABASE [video02] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [video02] SET DB_CHAINING OFF 
GO
ALTER DATABASE [video02] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [video02] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [video02]
GO
/****** Object:  User [video02]    Script Date: 12/12/2014 1:09:50 AM ******/

GO
/****** Object:  Schema [video02]    Script Date: 12/12/2014 1:09:50 AM ******/
CREATE SCHEMA [video02]
GO
/****** Object:  Table [dbo].[Student]    Script Date: 12/12/2014 1:09:50 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Student](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Ime] [nvarchar](50) NULL,
	[Prezime] [nvarchar](50) NULL,
	[BrojIndeksa] [nvarchar](50) NULL,
	[IsDeleted] [bit] NULL,
 CONSTRAINT [PK_Student] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET IDENTITY_INSERT [dbo].[Student] ON 

GO
INSERT [dbo].[Student] ([Id], [Ime], [Prezime], [BrojIndeksa], [IsDeleted]) VALUES (1, N'Adil', N'Joldic', N'IB00001', 0)
GO
SET IDENTITY_INSERT [dbo].[Student] OFF
GO
USE [master]
GO
ALTER DATABASE [video02] SET  READ_WRITE 
GO
