// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebApplication5.Db;

namespace WebApplication5.Migrations
{
    [DbContext(typeof(VirtualDB))]
    [Migration("20171204150045_InicijalnaDB")]
    partial class InicijalnaDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication5.EntityModels.Opstina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Opis");

                    b.HasKey("Id");

                    b.ToTable("_opstine");
                });

            modelBuilder.Entity("WebApplication5.EntityModels.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ime");

                    b.Property<int?>("OpstinaId");

                    b.Property<string>("Prezime");

                    b.HasKey("Id");

                    b.HasIndex("OpstinaId");

                    b.ToTable("_studenti");
                });

            modelBuilder.Entity("WebApplication5.EntityModels.Student", b =>
                {
                    b.HasOne("WebApplication5.EntityModels.Opstina", "Opstina")
                        .WithMany()
                        .HasForeignKey("OpstinaId");
                });
#pragma warning restore 612, 618
        }
    }
}
